CREATE DATABASE catalog_starter_test OWNER catalog;
CREATE DATABASE catalog OWNER catalog;
CREATE DATABASE catalog_test OWNER catalog;
CREATE DATABASE orders OWNER catalog;
CREATE DATABASE orders_test OWNER catalog;
CREATE DATABASE notifications OWNER catalog;
CREATE DATABASE notifications_test OWNER catalog;
CREATE DATABASE payments OWNER catalog;
CREATE DATABASE payments_test OWNER catalog;
